### ISSUE TITLE
diagrams-builder not in stack LTS 7

### ISSUE THREAD

**Issue by cdupont** [diagrams/diagrams-builder#30]
diagrams-builder is not in stack LTS 7.14. Do you know why?
https://www.stackage.org/lts-7.14

**Comment by byorgey** [comment]
Yes, it's because LTS-7 was released at a point when there were some build problems with `diagrams-builder`.  Note that LTS-7 still has diagrams-1.3.  They don't add or upgrade packages within the same major LTS version.  However `diagrams-builder` is successfully building on Stackage: https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L409 .  So when LTS-8 comes out it will include `diagrams-builder` again (as well as all the diagrams-1.4 packages).  In the meantime you can either add `diagrams-builder` to your `extra-deps` field, or depend on Stackage `nightly`.
